### ISSUE TITLE
Add dedicated button for scanning new location to nav bar

### ISSUE THREAD

**Issue by ndrwksr** [zerobase-io/smart-tracing#1]
Fulfilled User Story:
As a user, I need to be able to quickly scan a new QR code so that registering the locations I've been is as convenient as fast as possible.

Motivation:
The largest user category will be individuals registering the locations they have visited. People visiting, say, grocery stores are likely to want to be in and out as fast as possible to minimize risk of exposure, and so are unlikely to spend more than ~10 seconds getting their phone out and scanning a QR code. The faster and easier we make doing so, the more likely people are to be diligent in their usage of the system.

**Comment by JohnCLo** [comment]
Yes this a great suggestion. Scan is currently hidden in the menu button. However the user flow we are pushing for during training is for Users to use their default camera app, point it at the QR, click the prompt and done. Less than 2 seconds. We estimate 8% of smartphone default camera apps do not have QR scanning ability - would be interesting to research this coverage

**Comment by ndrwksr** [comment]
Adding in simple functionality to scan QR codes from a mobile app would be close to trivial to cover that last 8%. Wouldn't be as seamless are your proposal, but a nice backup for those who need it.

**Comment by JohnCLo** [comment]
<img width="340" alt="Screen Shot 2020-03-19 at 10 10 21 PM" src="https://user-images.githubusercontent.com/1709234/77115468-af481c80-6a2e-11ea-9e61-0bd674cae4c0.png">
