### ISSUE TITLE
Basic SEO

### ISSUE THREAD

**Issue by miketitchen** [zerobase-io/smart-tracing#121]
* add meta description
* static links for Information -> Overview, Individuals, Business and Healthcare

**Comment by JohnCLo** [comment]
Hey @miketitchen, for the FE devs do you mind copy and pasting the meta description tags and they will update. Thanks

**Comment by alh2202** [comment]
Not sure how to do this

**Comment by miketitchen** [comment]
The  static links are already done on staging. These are the meta tags to add to the following pages, which need to be added near the top of the HTML document:

/ (homepage)
`<meta name="Description" content="Zerobase is a free, privacy-first contact tracing platform that empowers both individuals and local officials to stop the spread of COVID-19.">`

/about
`<meta name="Description" content="Everything you need to know about Zerobase.">`

/privacy
`<meta name="Description" content="Zerobase is designed from the ground up to put your privacy first.">`

/individual
`<meta name="Description" content="Information for individuals">`

/community
`<meta name="Description" content=“Information for communities and public officials">`

/businesses
`<meta name="Description" content=“Information for businesses and public locations">`

/testing
`<meta name="Description" content=“Information for healthcare and testing sites">`

**Comment by miketitchen** [comment]
Let's also update the `<title>` tags. "Zerobase - Smart Tracing That Keeps Communities Safe" is fine for the homepage, but we should change it for the other static pages.

For instance, the About page should have a title tag of "About"
