### ISSUE TITLE
Brave Browser Pixel 3 

### ISSUE THREAD

**Issue by IsseiBelial** [zerobase-io/smart-tracing#125]
Brave Browser - Updated newest available version
checked privacy policy, put in number. Does not submit when clicked. 

![brave brower](https://user-images.githubusercontent.com/55858573/78217455-23041380-748a-11ea-89ca-da06b638f25f.png)

**Comment by JohnCLo** [comment]
Zerobase.io is actually an older version where this functionality is intentionally disabled. This is resolved in staging.zerobase.io
