### ISSUE TITLE
Staging.zerobase.io Slack Link Inactive -- Need New One

### ISSUE THREAD

**Issue by IsseiBelial** [zerobase-io/smart-tracing#127]
![20d845b1-e456-4edb-894b-6174ea195247](https://user-images.githubusercontent.com/55858573/78256119-24533180-74c6-11ea-9ec1-8762ae08e658.png)

**Comment by JohnCLo** [comment]
Related to https://github.com/zerobase-io/smart-tracing/issues/142
and resolved by https://github.com/zerobase-io/smart-tracing/pull/157. Thank you!
