### ISSUE TITLE
Image rendering bug on About page

### ISSUE THREAD

**Issue by twoangstroms** [zerobase-io/smart-tracing#130]
On a desktop Mac (Mojave OS, latest Safari but not latest Firefox beta), ZerobaseLogo_light.png renders incorrectly. (Trying to attach image but it's stretched vertically.)

**Comment by twoangstroms** [comment]
![Screen Shot 2020-04-02 at 7 41 54 AM](https://user-images.githubusercontent.com/62673202/78266872-31b6ee80-74bb-11ea-8c1e-252f53924740.png)

**Comment by JohnCLo** [comment]
Related to #188
