### ISSUE TITLE
Create a feedback form

### ISSUE THREAD

**Issue by eriksogn** [zerobase-io/smart-tracing#143]
An extremely simple, no barrier to entry feedback form
This will be powered by an embedded AirTable form

This form will live at https://zerobase.io/feedback
There will also be a modal dialog which can pop up from anywhere, starting with the scan successful screen.

#### Feedback form design
We are committed to stopping covid-19 in your community, and your feedback helps us improve.
Your feedback is not connected to your account. If you would like to hear from us, please include your email or phone number.

Big text box
Submit

Smart Tracing That Keeps Communities Safe
Built for real humans in need by real humans who care.

Privacy Policy

**Comment by twoangstroms** [comment]
In the shared Airtable workspace as "Zerobase Feedback Form"; anyone invited as a Creator in that workspace should have full access. A creator link for any email (do not share with anyone outside the project) is https://airtable.com/invite/l?inviteId=invDyz0hvPmk3dbYQ&inviteToken=338054303b203e69572db59cb940a101f5ac8a32a0738a1dc4548909cd4bd3d3
