### ISSUE TITLE
Create a contact us form

### ISSUE THREAD

**Issue by eriksogn** [zerobase-io/smart-tracing#145]
A more complete contact us form when people for when people likely expect a response
This will be powered by an embedded Airtable form
This will live at: zerobase.io/contact

#### Design
Intro message

Optional: Name
Email required
Optional: Phone
Dropdown
Big text box

You can also reach us at  info@zerobase.io

Thank you message

#### Contact Form Links
In our header
In our footer

**Comment by twoangstroms** [comment]
In shared Airtable workspace as "Contact Us Form". Should be usable with Creator privileges to anyone in that workspace. If not, the Creator link (do not share) is https://airtable.com/invite/l?inviteId=invhD8WFpk1bKKZDU&inviteToken=47397b269d07400ba3c6f8299419bba840a689a1516f4f44a4d53c74d3b75c19
