### ISSUE TITLE
Layout for form pages on mobile

### ISSUE THREAD

**Issue by twoangstroms** [zerobase-io/smart-tracing#164]
At least on iPhone XR, latest iOS and Safari as well as Firefox, there's a blank footer-like space at the bottom of the screen that can obscure form content. Attaching screen shots. 

![IMG_6034](https://user-images.githubusercontent.com/62673202/78374255-76588d80-7580-11ea-88f5-4a40dafd684f.PNG)
![IMG_6035](https://user-images.githubusercontent.com/62673202/78374259-7789ba80-7580-11ea-8007-efa1e0cabd54.PNG)

**Comment by JohnCLo** [comment]
This is an issue with the embed code. Should be changed to "height: 100%"
