### ISSUE TITLE
About page - Link not working

### ISSUE THREAD

**Issue by cndiaye6** [zerobase-io/smart-tracing#171]
"More about contact tracing" link doesn't go anywhere

**Comment by alh2202** [comment]
@JohnCLo the link is correct - is this a staging issue?

`a.btn.btn-outline-dark.font-weight-normal(href='https://www.who.int/features/qa/contact-tracing/en/' role="button" style="border-color: #65C6E1; color:#65C6E1") More about contact tracing`

**Comment by JohnCLo** [comment]
@alh2202 Yes this seems to be staging being a little bit out of sync. It will take a few minutes to catch up. Also, please remember to refresh your cache - vue.js is very aggressive with caching
@cndiaye6 resolved in https://github.com/zerobase-io/smart-tracing/pull/161
