### ISSUE TITLE
Privacy Policy Page Issues

### ISSUE THREAD

**Issue by cndiaye6** [zerobase-io/smart-tracing#183]
- Quotation mark missing after platform in the 3rd line of the intro

- In "Data concerning health" paragraph GDPR acronym used before it's defined on the page (the defining happens in the next paragraph "Other special categories of data"

- In "How to contact us", a space is needed between "at" and david's email

**Comment by yonglid** [comment]
@alh2202 & @JohnCLo took a look and it seems everything has been resolved for this issue already -- do we want to close?
