### ISSUE TITLE
Businesses page: hyphen missing from "privacy-first" in "privacy-first contact tracing"

### ISSUE THREAD

**Issue by cndiaye6** [zerobase-io/smart-tracing#216]
in the bolded paragraph under the title beginning "Zerobase is a..."

**Comment by JohnCLo** [comment]
Looping in @twoangstroms on what the correct usage of the hyphen is. Blocking this issue until copy editors reach consensus:

Related to https://github.com/zerobase-io/smart-tracing/issues/162
Related to https://github.com/zerobase-io/smart-tracing/issues/133

Please also see how many times this has gone back and forth:
https://github.com/zerobase-io/smart-tracing/issues?q=privacy+first

**Comment by twoangstroms** [comment]
There are two different cases possibly being conflated:

1. Use as a modifier (Example: "Privacy-first application"): this is a compound adjective, as as such, should be hyphenated.

2. Stand alone (Example: "We value privacy first" has "first" modify "privacy", or "Privacy First" when it's not modifying anything as in a footer heading): here the phrase does not modify anything, and should not be hyphenated.

See https://owl.purdue.edu/owl/general_writing/punctuation/hyphen_use.html
