### ISSUE TITLE
ZerobaseLogo_icon.png resize issue in responsive design

### ISSUE THREAD

**Issue by twoangstroms** [zerobase-io/smart-tracing#226]
It's fine at widescreen desktop/laptop, fine resized to mobile viewport, but there's a point in between where the ZerobaseLogo_icon.png pops up super large. Images below.

![Screen Shot 2020-04-05 at 4 12 34 PM](https://user-images.githubusercontent.com/62673202/78512435-44e6ea00-7759-11ea-8473-599db1eae398.png)
![Screen Shot 2020-04-05 at 4 12 41 PM](https://user-images.githubusercontent.com/62673202/78512438-49ab9e00-7759-11ea-898a-bdd946b09d72.png)
![Screen Shot 2020-04-05 at 4 12 50 PM](https://user-images.githubusercontent.com/62673202/78512451-6a73f380-7759-11ea-9b52-918346c43b82.png)

**Comment by twoangstroms** [comment]
It may not be obvious in the above screen shots, but the first is desktop, the bottom is a very narrow viewport so the logo icon looks fine, but in the middle the zerobase icon logo is much larger.

**Comment by JohnCLo** [comment]
The breakpoints initially set were too wide lg as opposed to md. I updated the breakpoints so on tablets the desktop layout is preserved as opposed to the single column mobile layout - this resolves the issue where the middle zerobase icon looks too large as it attempts to fill up a single column layout
