### ISSUE TITLE
Simplify the menubar

### ISSUE THREAD

**Issue by eriksogn** [zerobase-io/smart-tracing#229]
I suggest simplifying the menubar to:

Home About Privacy Contact

I do not believe we need "Use Cases" in the menu. The use cases are already represented on the landing page and in the footer. This will cause the header to fit on mobile.

**Comment by JohnCLo** [comment]
Please refresh your cache and view the latest staging.zerobase.io
A mobile specific menu has been created to deal with this scenario in the merged PR: https://github.com/zerobase-io/smart-tracing/pull/218

<img width="347" alt="Screen Shot 2020-04-06 at 3 33 08 PM" src="https://user-images.githubusercontent.com/1709234/78571733-d5d7c700-7826-11ea-8bf6-34add69000bc.png">

**Comment by eriksogn** [comment]
Great work! I agree with closing this issue now.
