### ISSUE TITLE
Phone number phone component doesn't tell user how to format phone number, leading to submission failure

### ISSUE THREAD

**Issue by twoangstroms** [zerobase-io/smart-tracing#336]
No hint text in text entry field but form rejects phone number without specific entry format.

Instead of "Phone Number" as hint text, show (555) 555-1212 if that format is required. I entered 5551212 and the form failed, but had to guess that 555 5551212 would work.

**Comment by twoangstroms** [comment]
I went through and tested all the content blockers on and off. iPhone XR, iOS 13.4.1

Stalls on Connecting if on:
1Blocker
Nomorobo (that’s weird)

Allows scan to work:
Better
Crystal
Unobstruct

**Comment by JohnCLo** [comment]
Could you leave a screenshot of where this specific entry field is located? On the registration form or notification form?
