### ISSUE TITLE
Content Updates

### ISSUE THREAD

**Issue by eriksogn** [zerobase-io/smart-tracing#48]
Home Page:

https://github.com/zerobase-io/About-Us-Onboarding/blob/master/pages/home.md

In the navigation bar at the top of the page, change “User Case” to “Information for…”

Change "Updates" to "News" and move it to the right of "Notifications"

Add "Contact" and either have it go to our info email.

Add “Volunteers” under drop down for “Information for…” & link to https://github.com/zerobase-io/About-Us-Onboarding

Individuals:
https://github.com/zerobase-io/About-Us-Onboarding/blob/master/pages/individuals.md

Businesses and Public Locations:
https://github.com/zerobase-io/About-Us-Onboarding/blob/master/pages/businesses.md

Healthcare:
https://github.com/zerobase-io/About-Us-Onboarding/blob/master/pages/healthcare.md

**Comment by JohnCLo** [comment]
Moved the following to the Smart-Trace Wiki for now:
Individuals ->
https://github.com/zerobase-io/smart-tracing/wiki/Use-Case-:-Individuals
Businesses and Public Locations ->
https://github.com/zerobase-io/smart-tracing/wiki/Use-Case:-Businesses-&-Public-Locations
Healthcare ->
https://github.com/zerobase-io/smart-tracing/wiki/Use-Case:-Healthcare

Will first link to FE template and then create specific pages, once FE v1 stack is stable
